### ISSUE TITLE
CLI/Docs unclear for new user

### ISSUE THREAD

**Issue by bennysce** [cschroeter/park-ui#157]
As a newcomer the cli this question doesn't make much sense:

- What is your import alias for utilities?: [~/lib]

What kind of utilities are expected?

Continuing on reading the getting started guide (https://park-ui.com/docs/tailwind/overview/getting-started/) it seems to assume I have something called styled in that lib directory?

I get "Can't resolve '~/lib/styled'" when running react.

Can't find anything in the docs regarding what I should have installed there and the CLI doesn't seem to have helped with it. Is it dependent on styled-components or something?

EDIT: I found example files in the Next example (which I'm not using). Also it seems to depend on typescript. Is that true? Or can I remove the types and use it with regular js.

**Comment by cschroeter** [comment]
@bennysce 

Thansk for taking your time to create this issue. The component snippets provided often need to import a helper function.
In TypeScript there is a feature called `Path Aliases` that allows you to uniform the import statements no matter where you are in your source code folder.

So instead of `../../../lib/helper-fn` you can simply write `~/lib/helper-fn`

I will update the Tailwind examples in the days so I hope this gets a bit clearer.
