### ISSUE TITLE
can we get qwik support please?

### ISSUE THREAD

**Issue by LazyClicks** [cschroeter/park-ui#17]
any chance to support the new javascript framework qwik?

**Comment by naorpeled** [comment]
@cschroeter 
would love to help with this,
any pointers on how to do so?

**Comment by cschroeter** [comment]
Hey @naorpeled,

Park UI is eventually based on [Zag.js](https://zagjs.com/)
All the components (machines) are in general framework agnostic. Since I'm not so familiar with qwik I can only point you to what already has been discussed in the forum: https://github.com/chakra-ui/zag/discussions/392

I would be more than happy to add more frameworks in Ark ;)
