### ISSUE TITLE
CLI sometimes generate a .ts, sometimes generate a .tsx

### ISSUE THREAD

**Issue by 6qat** [cschroeter/park-ui#183]
CLI sometimes generate a .tsx, sometimes generate a .ts file for the component. The picture bellow shows a slider.ts on the left, and slider .tsx on the right. Both generated by the cli. The wierder part is that the .ts one is coded with withContext()  call functions, and the .tsx one is coded with directly using and styling the original ark components. One problem I got is that sometimes I happen to get both .ts and .tsx at the same time, which of course causes problems.

![image](https://github.com/cschroeter/park-ui/assets/1149271/85493c42-4b4f-4b50-a746-4429a2582b12)

**Comment by cschroeter** [comment]
@6qat,

Thank you for taking the time to report this issue. Allow me to clarify the situation.

As I started with Park UI, every snippet looked like the left side with a `.ts` extension. However, it became apparent that for some components like `Checkbox`, `Slider`, or `Switch`, a more encapsulated component design is preferable, enabling straightforward usage like `<Checkbox />`.

For additional insights into the rationale for this change, please refer to the [GitHub Issue](https://github.com/cschroeter/park-ui/issues/144).

Currently, all components have been normalized to use a `tsx` extension. It's important to view these snippets as a foundation rather than items requiring regular updates. If your existing setup works well for you, that's great, and no further action is necessary.

If you have any more questions, please feel free to ask. Cheers.

**Comment by 6qat** [comment]
Thank you very much for your second record time response and correction for me in just 2 days! Keep working in this awesome software. I think Park/Ark/Panda is a killer combo. Probably the foundation of the new Chakra framework. Congratulations and thank you very much for your spending time and effort to make this what it is today.
