### ISSUE TITLE
Create style context

### ISSUE THREAD

**Issue by JakeGinnivan** [cschroeter/park-ui#19]
I've just stumbled across this library, and thought i'd give it a spin while setting up a new project. I just wanted to know the plan around the create-style-context?

The use-client means it takes a step back from the benefits of ark + panda

**Comment by cschroeter** [comment]
@JakeGinnivan,

Your query on `create-style-context` is apt. The React ecosystem is indeed complex and your concern about server components is spot-on. A quick breakdown:

1. **UI Components**: All UI component libraries leverage client-side state and context; Ark UI is no different. These components have to live in the client due to the intrinsic need for event-handling and DOM interactions.

2. **Context Simplification**: Ark UI's context architecture simplifies the user-facing API. It efficiently connects each component part to the internal API, making it easier for multipart components to support various sizes and variants.

3. **Server Components**: React's server components don't yet support context. It's not a limitation of Ark UI but a current constraint in React itself.

Examples provided illustrate the utility of context in user-friendly API design:

**With Context:**
```tsx
<Tabs size="lg" variant="fill">
  <TabList>
    <TabTrigger value="react">React</TabTrigger>
    ...
  </TabList>
</Tabs>
```

**Without Context:**
```tsx
<Tabs size="lg" variant="fill">
  <TabList size="lg" variant="fill">
    <TabTrigger value="react" size="lg" variant="fill">React</TabTrigger>
    ...
  </TabList>
</Tabs>
```

The long-term plan around `create-style-context` aligns with React's updates on server components, especially once they start supporting context.

**Comment by JakeGinnivan** [comment]
Great thanks, I mainly wanted to raise this just to create visibility around what it's use was.
