### ISSUE TITLE
Switch component not showing thumb

### ISSUE THREAD

**Issue by DawidWraga** [cschroeter/park-ui#21]
The switch component is showing the label but not showing the thumb.

my code:

```tsx

export const SwitchDemo = (props: Omit<SwitchProps, 'children'>) => (
	<Switch defaultChecked {...props}>
		<SwitchControl>
			<SwitchInput />
			<SwitchThumb />
		</SwitchControl>
		<SwitchLabel>Label</SwitchLabel>
	</Switch>
);


```

The data-state html attribute seems to be changing correctly.
Other slot components are working, so I doubt it's the panda config. 

Is there any minimum parkui setup template for web code editors eg codepen?
This would help me to share minimum reproduction, and if I can't reproduce then I know it's probably bug on my end.

**Comment by cschroeter** [comment]
Thanks for taking your time to create this issue. I could not re-create the issue on my end. 

Could you dbl check that the snippet / recipe is up to date? https://park-ui.com/docs/components/switch

If so you can fork one of the [quickstart sandboxes](https://park-ui.com/docs/overview/getting-started) to reproduce the issue.

**Comment by cschroeter** [comment]
Closing due to inactivitiy

**Comment by QWu4xYV** [comment]
@cschroeter Thanks again for making this library! Unfortunately, I'm also running into this issue.

I tried to create a repro sandbox by clicking the link above, but it 404s, and when I googled for "park ui codesandbox", the only link that comes up is https://codesandbox.io/p/devbox/github/juliomuhlbauer/park-ui-nextjs/tree/main , which seems to be outdated because it shows an error "proxyState is not iterable". Do you have a recommended link to fork? I can also try to create one, but if you have an existing setup, that would be great!

**Comment by cschroeter** [comment]
@QWu4xYV 

I think best is to pick one of the getting started examples from here: https://park-ui.com/docs/panda/overview/getting-started

**Comment by isaac1400** [comment]
I am having the same problem. For some reason the styles are not being generated/added to the css output. Will try to debug it tomorrow

**Comment by cschroeter** [comment]
@isaac1400 

Please let me know what the issue was if you found it so I can update the docs to help others.
