### ISSUE TITLE
Not enough contrast between bg.canvas and bg.default

### ISSUE THREAD

**Issue by pixelmord** [cschroeter/park-ui#25]
Can you check that, on my monitor I cannot visually discern those two colors, I'd rather have `colors.gray-palette.50` + `colors.gray-palette.900`

**Comment by sozonome** [comment]
bg.canvas is #fcfcfc (very subtle white-gray)
while bg.default is pure white #fff

**Comment by cschroeter** [comment]
Haha - I just had a chat about this topc with my designer. The problem I see at the moment with the default gray.50 is that when applied it weakens the contrast for elements that not stand on a card (see attachment)

I am somewhat hesitant to change the default values of panda / tailwind.  So what I would like try out to bring the gray.25 closer to the gray.50. I gonna file a PR so you can share your opinion.

<img width="203" alt="image" src="https://github.com/cschroeter/park-ui/assets/1846056/f9a8fbe0-7b37-4525-afc5-58117c9258fa">


For the dark mode I agree with @pixelmord if you toggle the various grays in on the start page you can barely see a differents between them. If you change the canvas to 900 its more distinguishable but raises other issues since now you have to increase all other colors.

**Comment by cschroeter** [comment]
https://park-ui-website-i6kymf2gr-cschroeter-s-team.vercel.app/

Happy to hear your thoughts :)

**Comment by sozonome** [comment]
I see, I was using zinc gray palette so it's still distinguishable. The issue become apparent from neutral and stone gray palette. 

imho the change/update is very subtle and I'm still having hard time to notice

**Comment by pixelmord** [comment]
So in the image above I can see a slight difference between bg colors, but I reckon that if you would remove the border then it would be much harder. The same issue I see with the cards on the park-ui component demo:

![Screenshot 2023-08-30 at 20 54 32](https://github.com/cschroeter/park-ui/assets/224168/7b859803-bfd3-41e6-923d-6bd9c8be30a7)

I removed border and shadow and then I have to look really hard to see the difference, although my brain still knows that there should be a card visible

**Comment by pixelmord** [comment]
And for the dark mode colors, both default and canvas are set to 950 so there really is no difference :D

**Comment by pixelmord** [comment]
If I look at what e.g. Radix colors think about application and UI element background they seem to be fine with a bit more contrast.
[They recommend 0,1 for app and 3-5](https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale)

For example if I set the bg.canvas to `rgb(249,249,249)` a card with a white bg looks good even without border or shadow:

![Screenshot 2023-08-30 at 21 05 57](https://github.com/cschroeter/park-ui/assets/224168/0c7b5abe-c62e-4363-a57d-e61a1212dc70)

**Comment by cschroeter** [comment]
I defintively can see the value in iterating over this topic but for now I'm closing this issue and concentrate to bring more examples, framework integration guides and other improvements to the Park UI
