### ISSUE TITLE
Ability to use Panda CSS theme colors in createPreset

### ISSUE THREAD

**Issue by juliomuhlbauer** [cschroeter/park-ui#89]
When creating the preset with Park UI, it uses the radix pattern of color.1, color.2, ... color.12.
So it can't be used with Panda's theme (color.100, color.200).

**Comment by cschroeter** [comment]
@juliomuhlbauer 

That's correct and by design. The Radix Colors offer a greater possibilities when it comes to designing elements. To avoid confusion the Panda Colors have been replaced by the Radix colors.

However you still can bring back the Panda Colors if you prefer. Simply add the colors you like to your `panda.config.ts` like so:

```jsx
export default defineConfig({
  theme: {
    extend: {
      tokens: {
        colors: {
          rose: {
            50: { value: '#fff1f2' },
            //   etc
          },
        },
      },
    },
  },
})
```
